repos:
-   repo: http://github.com/ambv/black
    rev: 21.12b0
    hooks:
    -   id: black
        language_version: python3.9
-   repo: http://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: flake8
